import { Contact } from '../types/contact.ts';

export const INITIAL_DEMO_CONTACTS: Contact[] = [
  {
    id: '1e4c7a90-7d3e-436f-859a-1158d601b001',
    name: 'Mariana Silveira',
    email: 'mariana.silveira@techsolucoes.com.br',
    phone: '+55 11 98765-4321',
    company: 'Tech Soluções Inovadoras',
    role: 'Diretora de Tecnologia',
    category: 'Trabalho',
    notes: 'Ponto focal para projeto de integração do CRM e arquitetura cloud.',
    favorite: true,
    address: 'Av. Paulista, 1000 - Bela Vista, São Paulo - SP',
    tags: ['Tech', 'Cloud', 'Diretoria'],
    created_at: new Date(Date.now() - 86400000 * 12).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: '2f5d8b01-8e4f-447a-960b-2269e712c002',
    name: 'Carlos Eduardo Mendes',
    email: 'carlos.mendes@advocaciamendes.com.br',
    phone: '+55 21 99887-1122',
    company: 'Mendes & Associados',
    role: 'Consultor Jurídico',
    category: 'Parceiro',
    notes: 'Especialista em LGPD e conformidade de dados para sistemas web.',
    favorite: true,
    address: 'Rua da Assembleia, 50 - Centro, Rio de Janeiro - RJ',
    tags: ['Jurídico', 'LGPD', 'Contratos'],
    created_at: new Date(Date.now() - 86400000 * 8).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: '3a6e9c12-9f5a-458b-a71c-3370f823d003',
    name: 'Beatriz Vasconcelos',
    email: 'beatriz.v@varejoplus.com.br',
    phone: '+55 31 97654-8901',
    company: 'Varejo Plus Brasil',
    role: 'Gerente de Compras',
    category: 'Cliente',
    notes: 'Negociação trimestral de fornecimento. Prefere reuniões nas terças à tarde.',
    favorite: false,
    address: 'Av. Afonso Pena, 2400 - Savassi, Belo Horizonte - MG',
    tags: ['Varejo', 'Negociação', 'Key Account'],
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: '4b7f0d23-0a6b-469c-b82d-4481a934e004',
    name: 'Lucas Ferreira Ramos',
    email: 'lucas.ramos@designstudio.art',
    phone: '+55 41 99123-5566',
    company: 'Estúdio Prisma Design',
    role: 'Product Designer',
    category: 'Fornecedor',
    notes: 'Responsável pelo redesign do design system e protótipos de alta fidelidade.',
    favorite: false,
    address: 'Rua XV de Novembro, 800 - Centro, Curitiba - PR',
    tags: ['UI/UX', 'Design', 'Figma'],
    created_at: new Date(Date.now() - 86400000 * 4).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: '5c8a1e34-1b7c-470d-c93e-5592b045f005',
    name: 'Fernanda Albuquerque',
    email: 'fernanda.albuquerque@gmail.com',
    phone: '+55 19 98456-7890',
    company: 'Universidade Estadual',
    role: 'Professora e Pesquisadora',
    category: 'Pessoal',
    notes: 'Amiga do mestrado. Contato pessoal.',
    favorite: true,
    address: 'Barão Geraldo, Campinas - SP',
    tags: ['Pessoal', 'Academia', 'Mestrado'],
    created_at: new Date(Date.now() - 86400000 * 20).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: '6d9b2f45-2c8d-481e-da4f-6603c156a006',
    name: 'Rodrigo Nogueira',
    email: 'rodrigo@nogueiralogistica.com.br',
    phone: '+55 51 98111-2233',
    company: 'Nogueira Soluções Logísticas',
    role: 'Diretor Operacional',
    category: 'Cliente',
    notes: 'Contrato de transporte e frete corporativo.',
    favorite: false,
    address: 'Av. Ipiranga, 3200 - Porto Alegre - RS',
    tags: ['Logística', 'Supply Chain'],
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 2).toISOString(),
  }
];
